---
packages:
  - packages/*
catalog:
  '@lincy/eslint-config': ^5.5.0
  '@lincy/utils': ^0.6.2
  '@types/compression': ^1.7.5
  '@types/cookie-parser': ^1.4.8
  '@types/express': ^5.0.0
  '@types/jsonwebtoken': ^9.0.9
  '@types/markdown-it': ^14.1.2
  '@types/md5': ^2.3.5
  '@types/mockjs': ^1.0.10
  '@types/morgan': ^1.9.9
  '@types/multer': ^1.4.12
  '@types/node': ^22.13.10
  '@types/request-ip': ^0.0.41
  '@types/serve-favicon': ^2.5.7
  axios: ^1.8.2
  baidu-aip-sdk: ^4.16.16
  base64-img: ^1.0.4
  cheerio: 1.0.0
  compression: ^1.8.0
  concurrently: ^9.1.2
  connect-multiparty: ^2.2.0
  cookie-parser: ^1.4.7
  dayjs: ^1.11.13
  eslint: ^9.22.0
  express: ^4.21.2
  highlight.js: ^11.11.1
  jiti: ^2.4.2
  jsonwebtoken: ^9.0.2
  lint-staged: ^15.4.3
  lru-cache: ^11.0.2
  markdown-it: ^14.1.0
  markdown-it-toc-and-anchor: ^4.2.0
  md5: ^2.3.0
  mockjs: ^1.1.0
  mongoose: ^8.12.1
  mongoose-autopopulate: ^1.1.0
  morgan: ^1.10.0
  multer: 1.4.5-lts.1
  nodemon: ^3.1.9
  qiniu: ^7.14.0
  request-ip: ^3.3.0
  serve-favicon: ^2.5.0
  simple-git-hooks: ^2.11.1
  tsc-alias: ^1.8.11
  tslib: ^2.8.1
  tsx: ^4.19.3
  twig: ^1.17.1
  typescript: ^5.8.2
peerDependencyRules:
  ignoreMissing:
    - prettier
